# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(882, 777)
        MainWindow.setStyleSheet("background-color : rgb(250, 214, 165)\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.suffleBtn = QtWidgets.QPushButton(self.centralwidget)
        self.suffleBtn.setGeometry(QtCore.QRect(180, 660, 191, 51))
        self.suffleBtn.setStyleSheet("background-color : rgb(97, 118, 75);\n"
"font: 700 14pt \"Nanum Gothic\";\n"
"color : rgb(250, 214, 165);\n"
"font-size : 16px;\n"
"")
        self.suffleBtn.setObjectName("suffleBtn")
        self.AiBtn = QtWidgets.QPushButton(self.centralwidget)
        self.AiBtn.setGeometry(QtCore.QRect(470, 660, 191, 51))
        self.AiBtn.setStyleSheet("background-color : rgb(97, 118, 75);\n"
"font: 700 14pt \"Nanum Gothic\";\n"
"color : rgb(250, 214, 165);\n"
"font-size : 16px;\n"
"")
        self.AiBtn.setObjectName("AiBtn")
        self.Pgbar = QtWidgets.QLabel(self.centralwidget)
        self.Pgbar.setGeometry(QtCore.QRect(90, 590, 691, 31))
        self.Pgbar.setStyleSheet("background-color : rgb(128, 128, 128);\n"
"border: 1px solid black;\n"
"border-radius: 40px;")
        self.Pgbar.setObjectName("Pgbar")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(80, 40, 700, 520))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.widget = QtWidgets.QWidget(self.page)
        self.widget.setGeometry(QtCore.QRect(0, 0, 701, 521))
        self.widget.setStyleSheet("background-color : rgb(155, 161, 123);\n"
"border-radius : 5px;\n"
"")
        self.widget.setObjectName("widget")
        self.base = QtWidgets.QLabel(self.widget)
        self.base.setGeometry(QtCore.QRect(20, 20, 661, 481))
        self.base.setMinimumSize(QtCore.QSize(661, 481))
        self.base.setMouseTracking(False)
        self.base.setTabletTracking(False)
        self.base.setAcceptDrops(False)
        self.base.setAutoFillBackground(False)
        self.base.setStyleSheet("border-image: url(/Users/parkjunha/Desktop/Project/N-Puzzle/images/corgi.jpg);\n"
"border-radius : 10px; \n"
"opacity : 0.2;\n"
"")
        self.base.setText("")
        self.base.setPixmap(QtGui.QPixmap(":/cropImg/cropImg/corgi.jpg"))
        self.base.setScaledContents(True)
        self.base.setWordWrap(False)
        self.base.setOpenExternalLinks(False)
        self.base.setObjectName("base")
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setGeometry(QtCore.QRect(20, 20, 661, 481))
        self.widget_2.setMinimumSize(QtCore.QSize(661, 481))
        self.widget_2.setStyleSheet("background-color : rgba(255, 255, 255, 100);")
        self.widget_2.setObjectName("widget_2")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.puzzle_9 = QtWidgets.QPushButton(self.widget_2)
        self.puzzle_9.setMinimumSize(QtCore.QSize(220, 160))
        self.puzzle_9.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.puzzle_9.setStyleSheet("border-image: url(:/images/images/cropImg/corgi/corgi_2_2.jpg);\n"
"")
        self.puzzle_9.setText("")
        self.puzzle_9.setObjectName("puzzle_9")
        self.gridLayout.addWidget(self.puzzle_9, 2, 2, 1, 1)
        self.puzzle_8 = QtWidgets.QPushButton(self.widget_2)
        self.puzzle_8.setMinimumSize(QtCore.QSize(220, 160))
        self.puzzle_8.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.puzzle_8.setStyleSheet("border-image: url(:/images/images/cropImg/corgi/corgi_2_1.jpg);\n"
"")
        self.puzzle_8.setText("")
        self.puzzle_8.setObjectName("puzzle_8")
        self.gridLayout.addWidget(self.puzzle_8, 2, 1, 1, 1)
        self.puzzle_7 = QtWidgets.QPushButton(self.widget_2)
        self.puzzle_7.setMinimumSize(QtCore.QSize(220, 160))
        self.puzzle_7.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.puzzle_7.setStyleSheet("border-image: url(:/images/images/cropImg/corgi/corgi_2_0.jpg);\n"
"")
        self.puzzle_7.setText("")
        self.puzzle_7.setObjectName("puzzle_7")
        self.gridLayout.addWidget(self.puzzle_7, 2, 0, 1, 1)
        self.puzzle_6 = QtWidgets.QPushButton(self.widget_2)
        self.puzzle_6.setMinimumSize(QtCore.QSize(220, 160))
        self.puzzle_6.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.puzzle_6.setStyleSheet("border-image: url(:/images/images/cropImg/corgi/corgi_1_2.jpg);\n"
"")
        self.puzzle_6.setText("")
        self.puzzle_6.setObjectName("puzzle_6")
        self.gridLayout.addWidget(self.puzzle_6, 1, 2, 1, 1)
        self.puzzle_5 = QtWidgets.QPushButton(self.widget_2)
        self.puzzle_5.setMinimumSize(QtCore.QSize(220, 160))
        self.puzzle_5.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.puzzle_5.setStyleSheet("border-image: url(:/images/images/cropImg/corgi/corgi_1_1.jpg);\n"
"")
        self.puzzle_5.setText("")
        self.puzzle_5.setObjectName("puzzle_5")
        self.gridLayout.addWidget(self.puzzle_5, 1, 1, 1, 1)
        self.puzzle_4 = QtWidgets.QPushButton(self.widget_2)
        self.puzzle_4.setMinimumSize(QtCore.QSize(220, 160))
        self.puzzle_4.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.puzzle_4.setStyleSheet("border-image: url(:/images/images/cropImg/corgi/corgi_1_0.jpg);\n"
"")
        self.puzzle_4.setText("")
        self.puzzle_4.setObjectName("puzzle_4")
        self.gridLayout.addWidget(self.puzzle_4, 1, 0, 1, 1)
        self.puzzle_3 = QtWidgets.QPushButton(self.widget_2)
        self.puzzle_3.setMinimumSize(QtCore.QSize(220, 160))
        self.puzzle_3.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.puzzle_3.setStyleSheet("border-image: url(:/images/images/cropImg/corgi/corgi_0_2.jpg);\n"
"")
        self.puzzle_3.setText("")
        self.puzzle_3.setObjectName("puzzle_3")
        self.gridLayout.addWidget(self.puzzle_3, 0, 2, 1, 1)
        self.puzzle_2 = QtWidgets.QPushButton(self.widget_2)
        self.puzzle_2.setMinimumSize(QtCore.QSize(220, 160))
        self.puzzle_2.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.puzzle_2.setStyleSheet("border-image: url(:/images/images/cropImg/corgi/corgi_0_1.jpg);\n"
"")
        self.puzzle_2.setText("")
        self.puzzle_2.setObjectName("puzzle_2")
        self.gridLayout.addWidget(self.puzzle_2, 0, 1, 1, 1)
        self.puzzle_1 = QtWidgets.QPushButton(self.widget_2)
        self.puzzle_1.setMinimumSize(QtCore.QSize(220, 160))
        self.puzzle_1.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.puzzle_1.setStyleSheet("border-image: url(:/images/images/cropImg/corgi/corgi_0_0.jpg);\n"
"")
        self.puzzle_1.setText("")
        self.puzzle_1.setObjectName("puzzle_1")
        self.gridLayout.addWidget(self.puzzle_1, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.widget_3 = QtWidgets.QWidget(self.page_2)
        self.widget_3.setGeometry(QtCore.QRect(0, 0, 701, 521))
        self.widget_3.setStyleSheet("background-color : rgb(155, 161, 123);\n"
"border-radius : 5px;\n"
"")
        self.widget_3.setObjectName("widget_3")
        self.label_2 = QtWidgets.QLabel(self.widget_3)
        self.label_2.setGeometry(QtCore.QRect(20, 20, 661, 481))
        self.label_2.setMinimumSize(QtCore.QSize(661, 481))
        self.label_2.setMouseTracking(False)
        self.label_2.setTabletTracking(False)
        self.label_2.setAcceptDrops(False)
        self.label_2.setAutoFillBackground(False)
        self.label_2.setStyleSheet("border-image: url(/Users/parkjunha/Desktop/Project/N-Puzzle/images/corgi.jpg);\n"
"\n"
"border-radius : 10px; \n"
"opacity : 0.2;\n"
"")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/cropImg/cropImg/corgi.jpg"))
        self.label_2.setScaledContents(True)
        self.label_2.setWordWrap(False)
        self.label_2.setOpenExternalLinks(False)
        self.label_2.setObjectName("label_2")
        self.widget_4 = QtWidgets.QWidget(self.widget_3)
        self.widget_4.setGeometry(QtCore.QRect(20, 20, 661, 481))
        self.widget_4.setMinimumSize(QtCore.QSize(661, 481))
        self.widget_4.setStyleSheet("background-color : rgba(255, 255, 255, 100);")
        self.widget_4.setObjectName("widget_4")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_4)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.puzzle_10 = QtWidgets.QPushButton(self.widget_4)
        self.puzzle_10.setMinimumSize(QtCore.QSize(163, 118))
        self.puzzle_10.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.puzzle_10.setStyleSheet("border-image: url(:/images/images/cropImg/corgi16/corgi_0_3.jpg);")
        self.puzzle_10.setText("")
        self.puzzle_10.setObjectName("puzzle_10")
        self.gridLayout_2.addWidget(self.puzzle_10, 2, 5, 1, 1)
        self.puzzle_11 = QtWidgets.QPushButton(self.widget_4)
        self.puzzle_11.setMinimumSize(QtCore.QSize(163, 118))
        self.puzzle_11.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.puzzle_11.setStyleSheet("border-image: url(:/images/images/cropImg/corgi16/corgi_0_1.jpg);")
        self.puzzle_11.setText("")
        self.puzzle_11.setObjectName("puzzle_11")
        self.gridLayout_2.addWidget(self.puzzle_11, 2, 3, 1, 1)
        self.puzzle_12 = QtWidgets.QPushButton(self.widget_4)
        self.puzzle_12.setMinimumSize(QtCore.QSize(163, 118))
        self.puzzle_12.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.puzzle_12.setStyleSheet("border-image: url(:/images/images/cropImg/corgi16/corgi_2_1.jpg);")
        self.puzzle_12.setText("")
        self.puzzle_12.setObjectName("puzzle_12")
        self.gridLayout_2.addWidget(self.puzzle_12, 4, 3, 1, 1)
        self.puzzle_13 = QtWidgets.QPushButton(self.widget_4)
        self.puzzle_13.setMinimumSize(QtCore.QSize(163, 118))
        self.puzzle_13.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.puzzle_13.setStyleSheet("border-image: url(:/images/images/cropImg/corgi16/corgi_1_1.jpg);")
        self.puzzle_13.setText("")
        self.puzzle_13.setObjectName("puzzle_13")
        self.gridLayout_2.addWidget(self.puzzle_13, 3, 3, 1, 1)
        self.puzzle_14 = QtWidgets.QPushButton(self.widget_4)
        self.puzzle_14.setMinimumSize(QtCore.QSize(163, 118))
        self.puzzle_14.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.puzzle_14.setStyleSheet("border-image: url(:/images/images/cropImg/corgi16/corgi_2_0.jpg);")
        self.puzzle_14.setText("")
        self.puzzle_14.setObjectName("puzzle_14")
        self.gridLayout_2.addWidget(self.puzzle_14, 4, 2, 1, 1)
        self.puzzle_15 = QtWidgets.QPushButton(self.widget_4)
        self.puzzle_15.setMinimumSize(QtCore.QSize(163, 118))
        self.puzzle_15.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.puzzle_15.setStyleSheet("border-image: url(:/images/images/cropImg/corgi16/corgi_3_1.jpg);")
        self.puzzle_15.setText("")
        self.puzzle_15.setObjectName("puzzle_15")
        self.gridLayout_2.addWidget(self.puzzle_15, 6, 3, 1, 1)
        self.puzzle_16 = QtWidgets.QPushButton(self.widget_4)
        self.puzzle_16.setMinimumSize(QtCore.QSize(163, 118))
        self.puzzle_16.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.puzzle_16.setStyleSheet("border-image: url(:/images/images/cropImg/corgi16/corgi_3_0.jpg);")
        self.puzzle_16.setText("")
        self.puzzle_16.setObjectName("puzzle_16")
        self.gridLayout_2.addWidget(self.puzzle_16, 6, 2, 1, 1)
        self.puzzle_17 = QtWidgets.QPushButton(self.widget_4)
        self.puzzle_17.setMinimumSize(QtCore.QSize(163, 118))
        self.puzzle_17.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.puzzle_17.setStyleSheet("border-image: url(:/images/images/cropImg/corgi16/corgi_0_2.jpg);")
        self.puzzle_17.setText("")
        self.puzzle_17.setObjectName("puzzle_17")
        self.gridLayout_2.addWidget(self.puzzle_17, 2, 4, 1, 1)
        self.puzzle_18 = QtWidgets.QPushButton(self.widget_4)
        self.puzzle_18.setMinimumSize(QtCore.QSize(163, 118))
        self.puzzle_18.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.puzzle_18.setStyleSheet("border-image: url(:/images/images/cropImg/corgi16/corgi_1_0.jpg);")
        self.puzzle_18.setText("")
        self.puzzle_18.setObjectName("puzzle_18")
        self.gridLayout_2.addWidget(self.puzzle_18, 3, 2, 1, 1)
        self.puzzle_19 = QtWidgets.QPushButton(self.widget_4)
        self.puzzle_19.setMinimumSize(QtCore.QSize(163, 118))
        self.puzzle_19.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.puzzle_19.setStyleSheet("border-image: url(:/images/images/cropImg/corgi16/corgi_2_3.jpg);")
        self.puzzle_19.setText("")
        self.puzzle_19.setObjectName("puzzle_19")
        self.gridLayout_2.addWidget(self.puzzle_19, 4, 5, 1, 1)
        self.puzzle_20 = QtWidgets.QPushButton(self.widget_4)
        self.puzzle_20.setMinimumSize(QtCore.QSize(163, 118))
        self.puzzle_20.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.puzzle_20.setStyleSheet("border-image: url(:/images/images/cropImg/corgi16/corgi_1_3.jpg);")
        self.puzzle_20.setText("")
        self.puzzle_20.setObjectName("puzzle_20")
        self.gridLayout_2.addWidget(self.puzzle_20, 3, 5, 1, 1)
        self.puzzle_21 = QtWidgets.QPushButton(self.widget_4)
        self.puzzle_21.setMinimumSize(QtCore.QSize(163, 118))
        self.puzzle_21.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.puzzle_21.setStyleSheet("border-image: url(:/images/images/cropImg/corgi16/corgi_3_2.jpg);")
        self.puzzle_21.setText("")
        self.puzzle_21.setObjectName("puzzle_21")
        self.gridLayout_2.addWidget(self.puzzle_21, 6, 4, 1, 1)
        self.puzzle_22 = QtWidgets.QPushButton(self.widget_4)
        self.puzzle_22.setMinimumSize(QtCore.QSize(163, 118))
        self.puzzle_22.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.puzzle_22.setStyleSheet("border-image: url(:/images/images/cropImg/corgi16/corgi_3_3.jpg);")
        self.puzzle_22.setText("")
        self.puzzle_22.setObjectName("puzzle_22")
        self.gridLayout_2.addWidget(self.puzzle_22, 6, 5, 1, 1)
        self.puzzle_23 = QtWidgets.QPushButton(self.widget_4)
        self.puzzle_23.setMinimumSize(QtCore.QSize(163, 118))
        self.puzzle_23.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.puzzle_23.setStyleSheet("border-image: url(:/images/images/cropImg/corgi16/corgi_2_2.jpg);")
        self.puzzle_23.setText("")
        self.puzzle_23.setObjectName("puzzle_23")
        self.gridLayout_2.addWidget(self.puzzle_23, 4, 4, 1, 1)
        self.puzzle_24 = QtWidgets.QPushButton(self.widget_4)
        self.puzzle_24.setMinimumSize(QtCore.QSize(163, 118))
        self.puzzle_24.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.puzzle_24.setStyleSheet("border-image: url(:/images/images/cropImg/corgi16/corgi_0_0.jpg);")
        self.puzzle_24.setText("")
        self.puzzle_24.setObjectName("puzzle_24")
        self.gridLayout_2.addWidget(self.puzzle_24, 2, 2, 1, 1)
        self.puzzle_25 = QtWidgets.QPushButton(self.widget_4)
        self.puzzle_25.setMinimumSize(QtCore.QSize(163, 118))
        self.puzzle_25.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.puzzle_25.setStyleSheet("border-image: url(:/images/images/cropImg/corgi16/corgi_1_2.jpg);")
        self.puzzle_25.setText("")
        self.puzzle_25.setObjectName("puzzle_25")
        self.gridLayout_2.addWidget(self.puzzle_25, 3, 4, 1, 1)
        self.stackedWidget.addWidget(self.page_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 882, 24))
        self.menubar.setObjectName("menubar")
        self.menuMode = QtWidgets.QMenu(self.menubar)
        self.menuMode.setObjectName("menuMode")
        self.menuPhoto = QtWidgets.QMenu(self.menubar)
        self.menuPhoto.setObjectName("menuPhoto")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_8 = QtGui.QAction(MainWindow)
        self.action_8.setObjectName("action_8")
        self.action_15 = QtGui.QAction(MainWindow)
        self.action_15.setObjectName("action_15")
        self.action_24 = QtGui.QAction(MainWindow)
        self.action_24.setObjectName("action_24")
        self.actionCorgi = QtGui.QAction(MainWindow)
        self.actionCorgi.setObjectName("actionCorgi")
        self.actionCat = QtGui.QAction(MainWindow)
        self.actionCat.setObjectName("actionCat")
        self.actionMan = QtGui.QAction(MainWindow)
        self.actionMan.setObjectName("actionMan")
        self.menuMode.addAction(self.action_8)
        self.menuMode.addAction(self.action_15)
        self.menuMode.addAction(self.action_24)
        self.menuPhoto.addAction(self.actionCorgi)
        self.menuPhoto.addAction(self.actionCat)
        self.menuPhoto.addAction(self.actionMan)
        self.menubar.addAction(self.menuMode.menuAction())
        self.menubar.addAction(self.menuPhoto.menuAction())

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.puzzle_1.pressed.connect(MainWindow.movePuzzle) # type: ignore
        self.puzzle_4.pressed.connect(MainWindow.movePuzzle) # type: ignore
        self.puzzle_7.pressed.connect(MainWindow.movePuzzle) # type: ignore
        self.puzzle_2.pressed.connect(MainWindow.movePuzzle) # type: ignore
        self.puzzle_3.pressed.connect(MainWindow.movePuzzle) # type: ignore
        self.puzzle_6.pressed.connect(MainWindow.movePuzzle) # type: ignore
        self.puzzle_9.pressed.connect(MainWindow.movePuzzle) # type: ignore
        self.puzzle_5.pressed.connect(MainWindow.movePuzzle) # type: ignore
        self.puzzle_8.pressed.connect(MainWindow.movePuzzle) # type: ignore
        self.suffleBtn.pressed.connect(MainWindow.shuffle) # type: ignore
        self.action_8.triggered.connect(MainWindow.changeMode) # type: ignore
        self.puzzle_24.pressed.connect(MainWindow.movePuzzle) # type: ignore
        self.puzzle_11.pressed.connect(MainWindow.movePuzzle) # type: ignore
        self.puzzle_17.pressed.connect(MainWindow.movePuzzle) # type: ignore
        self.puzzle_10.pressed.connect(MainWindow.movePuzzle) # type: ignore
        self.puzzle_18.pressed.connect(MainWindow.movePuzzle) # type: ignore
        self.puzzle_14.pressed.connect(MainWindow.movePuzzle) # type: ignore
        self.puzzle_16.pressed.connect(MainWindow.movePuzzle) # type: ignore
        self.puzzle_13.pressed.connect(MainWindow.movePuzzle) # type: ignore
        self.puzzle_25.pressed.connect(MainWindow.movePuzzle) # type: ignore
        self.puzzle_20.pressed.connect(MainWindow.movePuzzle) # type: ignore
        self.puzzle_12.pressed.connect(MainWindow.movePuzzle) # type: ignore
        self.puzzle_23.pressed.connect(MainWindow.movePuzzle) # type: ignore
        self.puzzle_19.pressed.connect(MainWindow.movePuzzle) # type: ignore
        self.puzzle_15.pressed.connect(MainWindow.movePuzzle) # type: ignore
        self.puzzle_21.pressed.connect(MainWindow.movePuzzle) # type: ignore
        self.puzzle_22.pressed.connect(MainWindow.movePuzzle) # type: ignore
        self.action_15.triggered.connect(MainWindow.changeMode) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.suffleBtn.setText(_translate("MainWindow", "Suffle"))
        self.AiBtn.setText(_translate("MainWindow", "AI"))
        self.Pgbar.setText(_translate("MainWindow", "                                                                                            Pgbar"))
        self.menuMode.setTitle(_translate("MainWindow", "Mode"))
        self.menuPhoto.setTitle(_translate("MainWindow", "Photo"))
        self.action_8.setText(_translate("MainWindow", "8-Puzzle"))
        self.action_15.setText(_translate("MainWindow", "16-Puzzle"))
        self.action_24.setText(_translate("MainWindow", "24-Puzzle"))
        self.actionCorgi.setText(_translate("MainWindow", "Corgi"))
        self.actionCat.setText(_translate("MainWindow", "Cat"))
        self.actionMan.setText(_translate("MainWindow", "Man"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
